# Config file for MCMC run, might be updated later

setup:

  path:

    sangria: "LDC2_sangria_training_v2.h5"
    save_files: "./"  # Path to save files from which one wants to resume

run:

  resume: False       # Whether to resume run or start a new one
  use_gpu: True       # Whether to use gpu for current run

  n_iter: 10000       # Number of iterations
  maxT: 50            # Maximum temperature
  n_chains: 5         # Number of chains
